#!/bin/sh

# Copyright 2018 Linaro

#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are
#  met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following disclaimer
#    in the documentation and/or other materials provided with the
#    distribution.
#  * Neither the name of the  nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

LAVA='echo # '

LAVA_RAISE='echo # '

LAVA_SET='echo #'

if [ -n `which lava-test-case || true` ]; then
    LAVA='lava-test-case'
fi

if [ -n `which lava-test-raise || true` ]; then
    LAVA_RAISE='lava-test-raise'
fi

if [ -n `which lava-test-set || true` ]; then
    LAVA_SET='lava-test-set'
fi

command(){
    # setup command - will abort the test job upon failure.
    # expects two quoted arguments
    # $1 - valid lava test case name (no spaces)
    # $2 - the full command line to execute
    # Note: avoid trying to set environment variables.
    # use an explicit export.
    CMD=""
    PREFIX=$1
    shift
    while [ "$1" != "" ]; do
      CMD="${CMD} $1" && shift;
    done;
    if [ -n "$(which lava-test-case || true)" ]; then
        echo "${CMD}"
        $CMD && lava-test-case "${PREFIX}" --result pass || lava-test-raise "${PREFIX}"
    else
        echo "${CMD}"
        $CMD
    fi
}

testcase(){
    # test case command - will report a test case fail result upon failure.
    # expects two quoted arguments
    # $1 - valid lava test case name (no spaces)
    # $2 - the full command line to execute
    # Note: avoid trying to set environment variables.
    # use an explicit export.
    CMD=""
    PREFIX=$1
    shift
    while [ "$1" != "" ]; do
      CMD="${CMD} $1" && shift;
    done;
    if [ -n "$(which lava-test-case || true)" ]; then
        echo "$CMD"
        $CMD && lava-test-case "${PREFIX}" --result pass || lava-test-case "${PREFIX}"  --result fail
    else
        echo "$CMD"
        $CMD
    fi
}
